### ISSUE TITLE
Story: Download, Extract, and Write ETF List for NYSE.com into a file

### ISSUE THREAD

**Issue by kentimusrex** [WallStreetAnalytics/nyse_etf_extract#1]
As a financial minded user, I need to have an up to date list of all publicly available ETFs listed in the NYSE so that I may be able to query the ticker and get the name of the ETF from the file. 

Req:

1. Self contained executable code (can be a script to run) that can be run to collect all of the ETFs found listed on the NYSE.com website at (https://www.nyse.com/listings_directory/etf).
2. Scrape or RE the API call to be able to extract the ticker and the ticker description from the paginated table on the website.
3. Remove any special characters from the output (output validation)
4. Generate flat file, COMMA/TAB/PIPE delimited

Bonus Req:
1. Instead of a flat file generate one of the two following:
    a. AVRO file format - column names: id(NUMERIC), TICKER(ALPHA-NUMERIC), DESCRIPTION(ALPHA-NUMERIC) 
    b. Protobufv3 file format - Single file per ticker, file name is the ticker, schema defined as 
        message etf{ 
            required String ticker;
            required String description;
         }

**Comment by honggyu420** [comment]
#

**Comment by honggyu420** [comment]
Made the exporter here #2

**Comment by arprince** [comment]
why scrape when you can api and chill? https://api.nasdaq.com/api/screener/etf?page=3&exchange=NYSE

**Comment by kentimusrex** [comment]
because that api is being shutdown down and the one that replaces it costs money

**Comment by ZachtimusPrime** [comment]
Is this actually being used? I can write a version of it in node.js.

**Comment by nolineartime** [comment]
What's left for this issue? Are we ready to move forward?
